from datetime import datetime

from sqlalchemy import (
    Column,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    LargeBinary,
    String,
    Text,
    func,
)
from sqlalchemy.orm import relationship

from app.database import Base


class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)

    name = Column(String(100), nullable=False)

    phone = Column(
        String(20),
        unique=True,
        nullable=False,
        index=True,
    )

    # Email is optional
    email = Column(
        String(255),
        nullable=True,
        unique=True,
    )

    # We NEVER store the actual password
    password_hash = Column(
        String(255),
        nullable=False,
    )

    # USER or ADMIN
    role = Column(
        String(20),
        nullable=False,
        default="USER",
    )

    created_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    reports = relationship(
        "WaterReport",
        back_populates="user",
        cascade="all, delete-orphan",
    )


class WaterReport(Base):
    __tablename__ = "water_reports"

    id = Column(
        Integer,
        primary_key=True,
        index=True,
    )

    # Citizen who submitted the report
    user_id = Column(
        Integer,
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # Optional citizen description
    description = Column(
        Text,
        nullable=True,
    )

    # Actual image bytes stored inside PostgreSQL.
    # PostgreSQL will use BYTEA for this field.
    image_data = Column(
        LargeBinary,
        nullable=False,
    )

    # Example:
    # image/jpeg
    # image/png
    # image/webp
    image_type = Column(
        String(100),
        nullable=False,
    )

    latitude = Column(
        Float,
        nullable=False,
    )

    longitude = Column(
        Float,
        nullable=False,
    )

    # Citizen chooses 1 - 5
    severity_rating = Column(
        Integer,
        nullable=False,
    )

    # Generated by Member 3 smart engine
    category = Column(
        String(50),
        nullable=False,
        index=True,
    )

    # LOW / MEDIUM / HIGH / CRITICAL
    priority = Column(
        String(20),
        nullable=False,
        index=True,
    )

    # OPEN / IN_PROGRESS / RESOLVED
    status = Column(
        String(20),
        nullable=False,
        default="OPEN",
        index=True,
    )

    created_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    updated_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    resolved_at = Column(
        DateTime(timezone=True),
        nullable=True,
    )

    user = relationship(
        "User",
        back_populates="reports",
    )
